### ISSUE TITLE
Not compatible with UTF-8

### ISSUE THREAD

**Issue by ep98** [thirtybees/beesblog#13]
When I try to enter text in Czech or Cyrillic, blog module shows ????? instead of text:

System Environment:

Server information Linux #1 SMP Tue Aug 15 17:50:02 EDT 2017 x86_64
Server software version Apache
PHP version 7.0.24
Memory limit 512M
Max execution time 30

MySQL version 10.1.24-MariaDB-cll-lve
MySQL server localhost
MySQL name vinazbul_thbe550
MySQL user vinazbul_thbe550
Tables prefix tbep_
MySQL engine InnoDB
MySQL driver DbPDO

thirty bees version 1.0.3
Default community theme

**Comment by firstred** [comment]
Hey,

Thanks for your report.

It looks like thirty bees didn't enforce force full UTF-8 in the database, so instead your database has used the default collation instead.

Since it's pure database stuff that is also where it can be fixed. I recommend executing the following queries:
- Set the right default character set on the whole database: `` ALTER DATABASE <database name> CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci; ``
- Set the right character set on the blog category table: ``ALTER TABLE `PREFIX_bees_blog_category` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; ``
- Set the right character set on the image type table: `` ALTER TABLE `PREFIX_bees_blog_image_type` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; ``
- Finally, set the right character set on the blog post table: `` ALTER TABLE `PREFIX_bees_blog_post` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; ``

(Replace `PREFIX_` with your own prefix)

We will make sure thirty bees and this module will enforce UTF-8 instead of the database default, since that is more suitable for international software and almost every host seems to pick the smallest character set by default.

**Comment by ep98** [comment]
TB tables are ok, except those related to the beesblog:

bees_blog_category
bees_blog_category_lang
bees_blog_category_shop
bees_blog_image_type
bees_blog_image_type_shop
bees_blog_post
bees_blog_post_lang
bees_blog_post_shop

they are Latin1 and type MyISAM by default
rest of the tables are ok, and type InnoDB

Thanks for the assistance, could you please fix the module for the next releases ?

**Comment by Traumflug** [comment]
Apparently solved with pull request #29.

If not, please don't hesitate to re-open this issue.
