### ISSUE TITLE
Bees blog entries does not included in sitemap generated

### ISSUE THREAD

**Issue by DaoKakao** [thirtybees/beesblog#31]
The problem with module for sitemap creating and bees blog module.

Sitemap module recognizes beesblog installed, i.e. on the settings page appears a checkbox for beesblog posts/categories include/exclude, but it won't generate real sitemap - there's no any entry related to bees blog in the generated xml.

**Comment by selwynorren** [comment]
Howdy, how did you install the beesblog? When I ran the standard upgrades, it did not work for me, Not sure why, however when I compared the files here in Github and what was uploaded on my server I could see there was a difference.

I brought about the changes manually, and since then I have had no issues at all with the sitemap generation.

I would suggest compare your files on the server with the ones hosted here and see if these indeed match up, especially beesblog.php from about line 423

**Comment by getdatakick** [comment]
Problem was in hook GSitemapAppendUrls  not being registered during installation. That's fixed in f104eace8bb2fd5fa75af7c4411966d4a449a9e9.

I'll keep this issue opened because the fix will work for new installations only. Those who already installed the module are still affected, we need some migration for them
