### ISSUE TITLE
Cannot add new category in Bees blog module

### ISSUE THREAD

**Issue by Hedgehog85** [thirtybees/beesblog#53]
Whenever I try to add a new category in blog module, I got 500 error. Server logs show the following error:

[Fri Jan 04 06:41:22.389934 2019] [:error] [pid 106490] [client ip:46291] PHP Notice: Uninitialized string offset: 5 in /var/www/www-root/data/www/domain.com/modules/beesblog/controllers/admin/AdminBeesBlogCategoryController.php on line 378, referer: http://domain.com/admin###/index.php?controller=AdminBeesBlogCategory&addbees_blog_category&token=c004163d7e98cfad041ebe500041765f
[Fri Jan 04 06:41:22.390009 2019] [:error] [pid 106490] [client ip:46291] PHP Fatal error: Cannot access empty property in /var/www/www-root/data/www/domain.com/classes/ObjectModel.php on line 306, referer: http://domain.com/admin###/index.php?controller=AdminBeesBlogCategory&addbees_blog_category&token=c004163d7e98cfad041ebe500041765f

**Comment by getdatakick** [comment]
@Hedgehog85 have you modified the module in any way?

Because I just can't comprehend how it's possible to get these error messages. 

The first notice complains about this [line](https://github.com/thirtybees/beesblog/blob/e4261585ec4d670ac2d7cb39b9219d4865a14f7b/controllers/admin/AdminBeesBlogCategoryController.php#L378). The `$name` variable simply can't have string value `5`, as it iterates over keys from known [array](https://github.com/thirtybees/beesblog/blob/e4261585ec4d670ac2d7cb39b9219d4865a14f7b/classes/BeesBlogCategory.php#L43).

The second error is just a continuation of this first problem.

On related note: this whole `switch` code block is quite unnecessary since fields don't have other field type than `TYPE_STRING`
